"""Add comment length and user_count fields in sumamry entity

Revision ID: 6539c59c294c
Revises: 
Create Date: 2024-04-27 00:00:37.353084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6539c59c294c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagesummary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_comment_length', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('users_commented_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagesummary', schema=None) as batch_op:
        batch_op.drop_column('users_commented_count')
        batch_op.drop_column('average_comment_length')

    # ### end Alembic commands ###
