"""modify image, annotation association

Revision ID: ae7c032d5168
Revises: 8f914417631d
Create Date: 2024-04-25 14:16:26.576851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7c032d5168'
down_revision = '8f914417631d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_annotation_association', schema=None) as batch_op:
        batch_op.alter_column('image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('annotation_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_annotation_association', schema=None) as batch_op:
        batch_op.alter_column('annotation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('image_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
