name: Python App CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 5000:5000
        env:
          DOCKER_DRIVER: overlay2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: "2.14.2"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check if Docker Compose is installed
        run: docker-compose --version

      - name: Run Unit and Integration Tests
        run: pytest tests/
      #
      #- name: Build and run Tests with Docker Compose
      #  run: |
      #    docker-compose -f docker-compose.yml up -d
      #    docker-compose -f docker-compose.yml exec annotations_app pytest tests/

      - name: Shutdown Docker Compose
        run: docker-compose -f docker-compose.yml down
